package com.itechnowizard.chotu.utils

import android.content.Context
import android.view.View
import com.itechnowizard.chotu.databinding.ToolbarBinding

object Constants {

     var ERROR_MESSAGE : String = ""
     var DOWNLOAD_URL : String = ""
     var IS_INTENT_HAVING_DATA = "Intent having data"
     var IS_BUYER = "isBuyer"
     var INTENT_ACTIVITY = "Activity"
     var INTENT_BUYER_ID = "BuyerId"
     var INTENT_SELLER_ID = "SellerId"
     var INTENT_BUYER_ACTIVITY = "Buyer Activity"
     var INTENT_SELLER_ACTIVITY = "Seller Activity"
     var INTENT_CONSIGNEE_ACTIVITY = "Consignee Activity"
     var INTENT_INVENTORY_ACTIVITY = "Inventory Details Activity"
     var INTENT_TRANSPORT_LIST_ACTIVITY = "Transport List Activity"
     var INTENT_INVOICE_LIST_ACTIVITY = "Invoice List Activity"
     var INTENT_SUPPLIER_ACTIVITY = "Supplier Activity"
     var INTENT_PRODUCT_ACTIVITY = "Product Activity"
     var INTENT_BANK_ACTIVITY = "Bank Activity"
     var INTENT_OTHER_ACTIVITY = "Other Activity"
     var INTENT_TRANSPORT_ACTIVITY = "Transport Activity"
     var INTENT_CONTACT_ACTIVITY = "Contact Activity"
     const val OK = "OK"
     const val INTENT_MODEL = "Model"
     const val INTENT_DATA = "Data"
     const val DOCUMENT_ID = "Document Id"
     const val USER_MOBILE_NUMBER = "USER MOBILE NUMBER"
     const val FIREBASE_DOCUMENT_LISTS = "Lists"
     const val FIREBASE_LEDGER = "Ledger"
     const val FIREBASE_DOCUMENT_PERSONAL_DETAILS = "Personal Details"
     const val EXPENSE = "Expense"
     const val SUPPLIER = "Supplier"
     const val TRANSPORT = "Transport"
     const val OTHER = "Other"
     const val BUYER = "Buyer"
     const val SELLER = "Seller"
     const val CONSIGNEE = "Consignee"
     const val TRANSPORT_LIST = "Transport List"
     const val INVOICE = "Invoice"
     const val PROFORMAINVOICE = "Proforma Invoice"
     const val QUOTATION = "Quotation"
     const val PAYMENTRECEIPT = "Payment Receipt"
     const val PAYMENTMADE = "Payment Made"
     const val DEBITNOTE = "Debit Note"
     const val CREDITNOTE = "Credit Note"
     const val CREDITOR = "Creditors"
     const val DEBTORS = "Debtors"
     const val INVENTORY = "inventory"
     const val PURCHASE = "Purchase"
     const val PRODUCT = "Product"
     const val BANK = "Bank"
     const val CONTACT = "Contact"
     const val ADD_CONTACT = "Add Contact"
     const val EDIT_CONTACT = "Edit Contact"
     const val RETURN_RESULT = "return_result"
     const val FIREBASE_TOTAL_AMOUNT = "totalAmount"
     const val FIREBASE_NAME = "name"

     const val NEW_USER = "New User"
     const val EXISTING_USER = "Existing User"
     const val FAILED = "Failed"

     const val REQUEST_TAKE_PICTURE = 1
     const val REQUEST_SELECT_IMAGE = 2
     const val PERMISSIONS_REQUEST_CAMERA_AND_STORAGE = 101

     const val TOOLBAR_CREATE_INVOCE = "Create Invoice"
     const val TOOLBAR_CREATE_PROFORMA = "Create Proforma"
     const val TOOLBAR_CREATE_QUOTATION = "Create Quotation"
     const val TOOLBAR_EDIT_QUOTATION = "Edit Quotation"
     const val TOOLBAR_CREATE_PURCHASE = "Create Purchase"
     const val TOOLBAR_CREATE_NEW= "Create New"
     const val TOOLBAR_NO_TITLE = "NO_TITLE"
     const val TOOLBAR_NO_MENU_TEXT = "NO_MENU_TEXT"
     const val TOOLBAR_EDIT_BOX = "Edit Box"
     const val TOOLBAR_APP_NAME = "Chotu"
     const val TOOLBAR_EXPENSES = "Expenses"
     const val TOOLBAR_EXPENSE = "Expense"
     const val TOOLBAR_PAYMENT_RECEIPT = "Payment Receipt"
     const val TOOLBAR_PAYMENT_MADE = "Payment Made"
     const val TOOLBAR_BUYER_LIST = "Buyer List"
     const val TOOLBAR_INVENTORY_LIST = "Inventory List"
     const val TOOLBAR_SELLER_LIST = "Seller List"
     const val TOOLBAR_CONSIGNEE_LIST = "Consignee List"
     const val TOOLBAR_TRANSPORT_LIST = "Transport List"
     const val TOOLBAR_INVOICE_LIST = "Invoice List"
     const val TOOLBAR_PURCHASE_LIST = "Purchase List"
     const val TOOLBAR_BANK_LIST = "Bank List"
     const val TOOLBAR_ADD_NEW = "Add New"
     const val TOOLBAR_ADD_BUYER = "Add Buyer"
     const val TOOLBAR_ADD_SELLER = "Add Seller"
     const val TOOLBAR_ADD_CONSIGNEE = "Add Consignee"
     const val TOOLBAR_ADD_TRANSPORT = "Add Transport"
     const val TOOLBAR_ADD_BANK = "Add Bank"
     const val TOOLBAR_Edit_BUYER = "Edit Buyer"
     const val TOOLBAR_Edit_SELLER = "Edit Seller"
     const val TOOLBAR_Edit_CONSIGNEE = "Edit Consignee"
     const val TOOLBAR_Edit_INVOICE = "Edit Invoice"
     const val TOOLBAR_Edit_PROFORMA = "Edit Proforma"
     const val TOOLBAR_Edit_PURCHASE = "Edit Purchase"
     const val TOOLBAR_Edit_CREDITNOTE = "Edit Credit Note"
     const val TOOLBAR_Edit_RECEIPT = "Edit Receipt"
     const val TOOLBAR_Edit_DEBITNOTE = "Edit Debit Note"
     const val TOOLBAR_Edit_BANK = "Edit Bank"
     const val TOOLBAR_ADD_PRODUCT = "Add Product"
     const val TOOLBAR_REPORTS = "Reports"
     const val TOOLBAR_EDIT_PRODUCT = "Edit Product"
     const val TOOLBAR_PRODUCT_LIST = "Product List"
     const val TOOLBAR_SAVE = "Save"
     const val TOOLBAR_UPDATE = "Update"
     const val TOOLBAR_FIRM_DETAILS = "Firm Details"
     const val TOOLBAR_OTHER_DETAILS = "Other Details"
     const val TOOLBAR_TRANSPORTATION_DETAILS = "Transportation Details"



}